/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labtrapra2;

/**
 *
 * @author vanne
 */
public class VentanaPrincipal extends javax.swing.JFrame {
private int numeroSecreto;
private String codigoSecretoStr;
private int contadorAyudas = 0;
private int contadorIntentos = 0;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        generarCodigoSecreto();
    }
private void generarCodigoSecreto() {
    java.util.Random random = new java.util.Random();
    numeroSecreto = random.nextInt(900) + 100;
    codigoSecretoStr = String.valueOf(numeroSecreto);
    
    imagen.setVisible(false);

    txtpass1.setText(String.valueOf(codigoSecretoStr.charAt(0)));
    txtpass2.setText(String.valueOf(codigoSecretoStr.charAt(1)));
    txtpass3.setText(String.valueOf(codigoSecretoStr.charAt(2)));

    txtpass1.setEchoChar('$');
    txtpass2.setEchoChar('$');
    txtpass3.setEchoChar('$');
    
    lblmensaje.setText("Por favor, ingresa exactamente 3 números.");
    imagen.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        Titulo = new javax.swing.JLabel();
        txtpass1 = new javax.swing.JPasswordField();
        txtpass2 = new javax.swing.JPasswordField();
        txtpass3 = new javax.swing.JPasswordField();
        lblmensaje = new javax.swing.JLabel();
        txtIntento = new javax.swing.JTextField();
        jbRevelar = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane2.setBackground(new java.awt.Color(51, 0, 51));

        Titulo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 51));
        Titulo.setText("Codigo Secreto");

        txtpass1.setText("jPasswordField1");

        txtpass2.setText("jPasswordField2");

        txtpass3.setText("jPasswordField3");
        txtpass3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpass3ActionPerformed(evt);
            }
        });

        lblmensaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblmensaje.setForeground(new java.awt.Color(255, 255, 0));
        lblmensaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        txtIntento.setBorder(javax.swing.BorderFactory.createTitledBorder("Escriba 3 digitos + Enter"));
        txtIntento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntentoActionPerformed(evt);
            }
        });

        jbRevelar.setText("Revelar");
        jbRevelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jbRevelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRevelarActionPerformed(evt);
            }
        });

        imagen.setBackground(new java.awt.Color(255, 255, 255));
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labtrapra2/icons/trofeo64.png"))); // NOI18N
        imagen.setText("jLabel2");
        imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jDesktopPane2.setLayer(Titulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txtpass1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txtpass2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txtpass3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(lblmensaje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txtIntento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jbRevelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(imagen, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txtIntento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jbRevelar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                        .addComponent(txtpass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtpass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtpass3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpass3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(txtpass1)
                    .addComponent(txtpass2))
                .addGap(18, 18, 18)
                .addComponent(lblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIntento, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbRevelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIntentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntentoActionPerformed
        String cadena = txtIntento.getText();
        
        if(cadena.length() == 0 || cadena.length() == 1 || cadena.length() == 2){
            javax.swing.JOptionPane.showMessageDialog(this,"Por favor ingresa 3 números");
            return;
        } else {
            if(codigoSecretoStr.compareTo(cadena) < 0){
                javax.swing.JOptionPane.showMessageDialog(this,"El número ingresado es mayor al código secreto");
                contadorIntentos++;
                return;
            }
            if(codigoSecretoStr.compareTo(cadena) > 0){
                javax.swing.JOptionPane.showMessageDialog(this,"El número ingresado es menor al código secreto");
                contadorIntentos++;
                return;
            }
            if(codigoSecretoStr.compareTo(cadena) == 0){
                javax.swing.JOptionPane.showMessageDialog(this,"El número ingresado es correcto!");
                imagen.setVisible(true);
                return;
            }
        }
    }//GEN-LAST:event_txtIntentoActionPerformed

    private void jbRevelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRevelarActionPerformed
          if (contadorAyudas >= 2) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay más Revelaciones!", "Mensaje", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    contadorAyudas++;

    if (contadorAyudas == 1) {
        txtpass1.setEchoChar((char) 0);
    } else if (contadorAyudas == 2) {
        txtpass2.setEchoChar((char) 0);
    }
    }//GEN-LAST:event_jbRevelarActionPerformed

    private void txtpass3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpass3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpass3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel imagen;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbRevelar;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JTextField txtIntento;
    private javax.swing.JPasswordField txtpass1;
    private javax.swing.JPasswordField txtpass2;
    private javax.swing.JPasswordField txtpass3;
    // End of variables declaration//GEN-END:variables
}
